//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class contributor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string passwd { get; set; }
        public string occupation { get; set; }
        public string experience { get; set; }
        public string phoneNum { get; set; }
    }
}
