//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager
    {
        public int id { get; set; }
        public string name { get; set; }
        public string passwd { get; set; }
        public string phoneNumber { get; set; }
        public string Gender { get; set; }
        public string Hobbies { get; set; }
        public string Gmail { get; set; }
    }
}
